name: 'ecommerce_analytics' # Nome mais descritivo que 'dbtproject'
version: '1.0.0'
config-version: 2

profile: 'dbtproject'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:        
  - "target"
  - "dbt_packages"
  - "dbt_spark"  

# --- CONFIGURAÇÕES GLOBAIS DE MODELOS ---
models:
  ecommerce_analytics:
    staging:
      +schema: silver
      +materialized: view 
    marts:
      +schema: gold
      +materialized: table
       
  
flags:
  use_managed_iceberg: true
  use_concurrent_microbatch: true
  use_materialization_v2: true